#!/bin/bash

source $ANGEL_HOME/bin/spark-on-angel-env.sh

$SPARK_HOME/bin/spark-submit \
    --master yarn \
    --conf spark.yarn.queue=default \
    --conf spark.ps.jars=$SONA_ANGEL_JARS \
    --conf spark.ps.instances=2 \
    --conf spark.ps.cores=1 \
    --conf spark.ps.memory=13g \
    --jars $SONA_SPARK_JARS\
    --name "LR-spark-on-angel" \
    --driver-memory 1g \
    --num-executors 2 \
    --executor-cores 1 \
    --executor-memory 13g \
    --class com.tencent.angel.spark.examples.basic.LR \
    $ANGEL_HOME/lib/spark-on-angel-examples-${ANGEL_VERSION}.jar \
    input:"hdfs://bach101:9000/user/root/angel-3.1.0-bin/data/a9a/a9a_123d_train.libsvm" \
    lr:0.1 
